// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: loboscontrol.proto

package controlplane

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Secret        string                 `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
	Backend       string                 `protobuf:"bytes,4,opt,name=backend,proto3" json:"backend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthParams) Reset() {
	*x = AuthParams{}
	mi := &file_loboscontrol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthParams) ProtoMessage() {}

func (x *AuthParams) ProtoReflect() protoreflect.Message {
	mi := &file_loboscontrol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthParams.ProtoReflect.Descriptor instead.
func (*AuthParams) Descriptor() ([]byte, []int) {
	return file_loboscontrol_proto_rawDescGZIP(), []int{0}
}

func (x *AuthParams) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AuthParams) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AuthParams) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *AuthParams) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

type Filters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filters) Reset() {
	*x = Filters{}
	mi := &file_loboscontrol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filters) ProtoMessage() {}

func (x *Filters) ProtoReflect() protoreflect.Message {
	mi := &file_loboscontrol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filters.ProtoReflect.Descriptor instead.
func (*Filters) Descriptor() ([]byte, []int) {
	return file_loboscontrol_proto_rawDescGZIP(), []int{1}
}

func (x *Filters) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Name struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Name) Reset() {
	*x = Name{}
	mi := &file_loboscontrol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Name) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Name) ProtoMessage() {}

func (x *Name) ProtoReflect() protoreflect.Message {
	mi := &file_loboscontrol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Name.ProtoReflect.Descriptor instead.
func (*Name) Descriptor() ([]byte, []int) {
	return file_loboscontrol_proto_rawDescGZIP(), []int{2}
}

func (x *Name) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListAllUsersReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserReply           `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllUsersReply) Reset() {
	*x = ListAllUsersReply{}
	mi := &file_loboscontrol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllUsersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllUsersReply) ProtoMessage() {}

func (x *ListAllUsersReply) ProtoReflect() protoreflect.Message {
	mi := &file_loboscontrol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllUsersReply.ProtoReflect.Descriptor instead.
func (*ListAllUsersReply) Descriptor() ([]byte, []int) {
	return file_loboscontrol_proto_rawDescGZIP(), []int{3}
}

func (x *ListAllUsersReply) GetUsers() []*UserReply {
	if x != nil {
		return x.Users
	}
	return nil
}

type UserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        *AuthParams            `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReply) Reset() {
	*x = UserReply{}
	mi := &file_loboscontrol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReply) ProtoMessage() {}

func (x *UserReply) ProtoReflect() protoreflect.Message {
	mi := &file_loboscontrol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReply.ProtoReflect.Descriptor instead.
func (*UserReply) Descriptor() ([]byte, []int) {
	return file_loboscontrol_proto_rawDescGZIP(), []int{4}
}

func (x *UserReply) GetParams() *AuthParams {
	if x != nil {
		return x.Params
	}
	return nil
}

var File_loboscontrol_proto protoreflect.FileDescriptor

const file_loboscontrol_proto_rawDesc = "" +
	"\n" +
	"\x12loboscontrol.proto\x12\floboscontrol\"d\n" +
	"\n" +
	"AuthParams\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x16\n" +
	"\x06secret\x18\x03 \x01(\tR\x06secret\x12\x18\n" +
	"\abackend\x18\x04 \x01(\tR\abackend\"#\n" +
	"\aFilters\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x1a\n" +
	"\x04Name\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"B\n" +
	"\x11ListAllUsersReply\x12-\n" +
	"\x05users\x18\x01 \x03(\v2\x17.loboscontrol.UserReplyR\x05users\"=\n" +
	"\tUserReply\x120\n" +
	"\x06params\x18\x01 \x01(\v2\x18.loboscontrol.AuthParamsR\x06params2\xd3\x01\n" +
	"\fControlPlane\x12>\n" +
	"\aAddUser\x12\x18.loboscontrol.AuthParams\x1a\x17.loboscontrol.UserReply\"\x00\x12H\n" +
	"\fListAllUsers\x12\x15.loboscontrol.Filters\x1a\x1f.loboscontrol.ListAllUsersReply\"\x00\x129\n" +
	"\bListUser\x12\x12.loboscontrol.Name\x1a\x17.loboscontrol.UserReply\"\x00B\x14Z\x12lobos/controlplaneb\x06proto3"

var (
	file_loboscontrol_proto_rawDescOnce sync.Once
	file_loboscontrol_proto_rawDescData []byte
)

func file_loboscontrol_proto_rawDescGZIP() []byte {
	file_loboscontrol_proto_rawDescOnce.Do(func() {
		file_loboscontrol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_loboscontrol_proto_rawDesc), len(file_loboscontrol_proto_rawDesc)))
	})
	return file_loboscontrol_proto_rawDescData
}

var file_loboscontrol_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_loboscontrol_proto_goTypes = []any{
	(*AuthParams)(nil),        // 0: loboscontrol.AuthParams
	(*Filters)(nil),           // 1: loboscontrol.Filters
	(*Name)(nil),              // 2: loboscontrol.Name
	(*ListAllUsersReply)(nil), // 3: loboscontrol.ListAllUsersReply
	(*UserReply)(nil),         // 4: loboscontrol.UserReply
}
var file_loboscontrol_proto_depIdxs = []int32{
	4, // 0: loboscontrol.ListAllUsersReply.users:type_name -> loboscontrol.UserReply
	0, // 1: loboscontrol.UserReply.params:type_name -> loboscontrol.AuthParams
	0, // 2: loboscontrol.ControlPlane.AddUser:input_type -> loboscontrol.AuthParams
	1, // 3: loboscontrol.ControlPlane.ListAllUsers:input_type -> loboscontrol.Filters
	2, // 4: loboscontrol.ControlPlane.ListUser:input_type -> loboscontrol.Name
	4, // 5: loboscontrol.ControlPlane.AddUser:output_type -> loboscontrol.UserReply
	3, // 6: loboscontrol.ControlPlane.ListAllUsers:output_type -> loboscontrol.ListAllUsersReply
	4, // 7: loboscontrol.ControlPlane.ListUser:output_type -> loboscontrol.UserReply
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_loboscontrol_proto_init() }
func file_loboscontrol_proto_init() {
	if File_loboscontrol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_loboscontrol_proto_rawDesc), len(file_loboscontrol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_loboscontrol_proto_goTypes,
		DependencyIndexes: file_loboscontrol_proto_depIdxs,
		MessageInfos:      file_loboscontrol_proto_msgTypes,
	}.Build()
	File_loboscontrol_proto = out.File
	file_loboscontrol_proto_goTypes = nil
	file_loboscontrol_proto_depIdxs = nil
}
